name: Daily News Collector

on:
  schedule:
    - cron: '0 21 * * *'  # 每天晚上9点运行

jobs:
  collect_news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run news collector
        run: python src/main.py