name: Daily News Collector

# 定时任务: 每天晚上9点运行
on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 第二步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # 第三步：安装依赖项
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 第四步：运行 Python 脚本并传递环境变量
      - name: Run Python Script
        run: python src/main.py
        env:
          PROXIES: ${{ secrets.PROXIES }}  # 引用 GitHub 密钥 PROXIES
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}  # 引用 GitHub 密钥 EMAIL_ADDRESS
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}  # 引用 GitHub 密钥 EMAIL_PASSWORD
          TO_EMAILS: ${{ secrets.TO_EMAILS }}  # 引用 GitHub 密钥 TO_EMAILS